# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - dev
      - fix/*
  pull_request:
    branches:
      - dev
      - fix/*

name: R-CMD-check

jobs:
  build_src_package:
    runs-on: ubuntu-22.04

    name: Build source R package

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: apt update
        run: |
          sudo apt-get update
        shell: bash

      - name: run sanitizer
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/krlmlr/rigraph-san:main
          options: --rm --platform linux/amd64 -v ${{ github.workspace }}:/rigraph
          run: |
            cd rigraph
            RDcsan CMD INSTALL . --no-byte-compile
            RDcsan -q -e 'Sys.setenv(TESTTHAT_PARALLEL=FALSE); testthat::test_local(filter = "^serialize$", reporter = "location", load_package = "installed")'
